### ISSUE TITLE
can you release the  newly created evaluation dataset

### ISSUE THREAD

**Issue by 2a3b4c** [Sierkinhane/BoxDiff#1]
can you release the  newly created evaluation dataset?

thanks a lot!!!

**Comment by Sierkinhane** [comment]
Here are the box annotations for the collected dataset https://github.com/Sierkinhane/BoxDiff/blob/master/docs/bbox_as_condition.json. We just use them as spatial conditions to synthesize images.

**Comment by Zhexin-Zhang** [comment]
Could you share the weights of the YOLOv4 model used to evaluate the result on your newly created dataset？
Thanks！

**Comment by Sierkinhane** [comment]
Hi, you can refer to [this repository](https://github.com/ZejianLi/LAMA) to obtain YOLO scores. It's important to note that layout-to-image evaluations typically use the 80 classes in COCO. As a result, we utilize YOLOv4 weights available [here](https://github.com/pjreddie/darknet/issues/2135#issuecomment-657199920).
