### ISSUE TITLE
Results looks same as the baseline

### ISSUE THREAD

**Issue by dain5832** [Sierkinhane/BoxDiff#12]
Hello, I tried to compare the results by setting the scale factor to 0, but it seems like the results don't vary much from scale_factor=20.
Did I do something wrong?

run_sd_boxdiff.py --prompt "as the aurora lights up the sky, a herd of reindeer leisurely wanders on the grassy meadow, admiring the breathtaking view, a serene lake quietly reflects the magnificent display, and in the distance, a snow-capped mountain stands majestically, fantasy, 8k, highly detailed" --P 0.2 --L 1 --seeds [2] --token_indices [3,12,21,30,46] --bbox [[1,3,512,202],[75,344,421,495],[1,327,508,507],[2,217,507,341],[1,135,509,242]] --refine False

![sd15_0_2](https://github.com/showlab/BoxDiff/assets/62231006/5e7921bd-02c1-4dd7-bdab-72c597d2d297)
![sd15_20_2](https://github.com/showlab/BoxDiff/assets/62231006/e8d84254-60b1-4a9c-a919-0df762464e4e)

**Comment by Sierkinhane** [comment]
Hi, have you tried more cases?

**Comment by dain5832** [comment]
Yes, and they showed similar results.
It seems like the results does not match with the image in the paper.
Maybe I did something wrong..

Could you check if it works fine in your environment?

![sd15_0_as the aurora lights](https://github.com/showlab/BoxDiff/assets/62231006/d8f4945c-53c8-455a-8ad4-73e9ed92d4e2)
![sd15_20_as the aurora lights](https://github.com/showlab/BoxDiff/assets/62231006/945fbc55-db59-4b2c-9b8a-7c65cf635282)

**Comment by dain5832** [comment]
Oh never mind. It was my bad.
Thanks for your help!

**Comment by Sierkinhane** [comment]
Hi, actually, there are differences if you look at the position of each object such as the location of reindeers. And you can try other prompts. Without latent updating directed by BoxDiff, the objects would be randomly positioned in the image.
