### ISSUE TITLE
Problem with Tkinter library

### ISSUE THREAD

**Issue by MrDasix** [Sierkinhane/BoxDiff#3]
I'm trying to replicate the setup and the examples that you show on the Readme, and i am currently having problems with the Tkinter library used in utils/drawer. The code crashes when trying to import the Library. I have been able to go round this problem commenting the calls from `draw_rectangle `and `DashedImageDraw `and not importing anything from `utils.drawer`, but i'm just wondering if there is something else to setup to make Tkinter available. Thanks

**Comment by Sierkinhane** [comment]
Hi, can you list the error information?

**Comment by MrDasix** [comment]
This is the problem that shows using the headless opencv library (opencv-python-headless)

![image](https://github.com/showlab/BoxDiff/assets/22715371/549d522d-b5a1-4219-9309-5d874b7ef9f0)

**Comment by Sierkinhane** [comment]
Hi, I did not encounter such a problem. Hope solutions at [here](https://stackoverflow.com/questions/48504746/importerror-libtk8-6-so-cannot-open-shared-object-file-no-such-file-or-direct) may help you.
