### ISSUE TITLE
About the degraded result

### ISSUE THREAD

**Issue by xiaominli1020** [Sierkinhane/BoxDiff#5]
Hi, thanks for your interesting work, and I have a try. However, the quality of the generated image is unsatisfactory.
![image](https://github.com/showlab/BoxDiff/assets/25433111/de114fdb-9f35-4743-b81e-4c3908f28eb9)
Given the prompt "A dog plays a ball, a cat is sleeping" and layouts of each subject, we cannot obtain results according to the layouts.

**Comment by Sierkinhane** [comment]
Hi, as the Stable Diffusion only operates on the latent space (64x64), the cross-attention maps are in a small resolution (and we only use the ones in 16x16). To some extent, it cannot deal with / control the generation of small objects. Maybe you can enlarge the bouding boxes to get better controllability.
