### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by fikry102** [Sierkinhane/BoxDiff#6]
I use python3.8.18. (`conda create -n boxdiff python=3.8`)
After `pip3 install -r requirements.txt` and install diffusers using `pip3 install -e .`,

run `CUDA_VISIBLE_DEVICES=0 python3 run_sd_boxdiff.py --prompt "A rabbit wearing sunglasses looks very proud"  --P 0.2 --L 1 --seeds [1,2,3,4,5,6,7,8,9] --token_indices [2,4] --bbox [[67,87,366,512],[66,130,364,262]]` :

1.
envs/boxdiff/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

2.
envs/boxdiff/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

3.
BoxDiff/diffusers/src/diffusers/models/modeling_utils.py", line 119, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for '../stable-diffusion-v1-4/unet/diffusion_pytorch_model.bin' at '../stable-diffusion-v1-4/unet/diffusion_pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by Sierkinhane** [comment]
Hi, can you check the checkpoint whether is completely downloaded?
