### ISSUE TITLE
How did you compute the T2I-similarity for the evaluation?

### ISSUE THREAD

**Issue by archmelow** [Sierkinhane/BoxDiff#7]
First of all, thank you for your wonderful research.
How is the T2I similarity computed between two embedded vectors? Could I ask if it was computed using the cosine similarity between them?
Thank you.

**Comment by Sierkinhane** [comment]
Exactly. I followed [CLIP](https://github.com/openai/CLIP) to get the similarity.

**Comment by archmelow** [comment]
> Exactly. I followed [CLIP](https://github.com/openai/CLIP) to get the similarity.

thank you for replying.
