### ISSUE TITLE
Could you share the weights of the YOLOv4 model pretrained with COCO-stuff dataset?

### ISSUE THREAD

**Issue by archmelow** [Sierkinhane/BoxDiff#8]
First, thank you for your wonderful research. 
It seems that you have conducted your research with the YOLOv4 model trained with COCO-stuff dataset.
I'm aiming to reproduce your paper's results on YOLO mAP score with the COCO-stuff dataset.
I'd like to know where you have downloaded the pretrained weights. Or if you have trained it yourself, could you please provide 
the pretrained weights to test your model with? I've been struggling to find YOLO model trained with COCO-stuff dataset. (Not the one with COCO, 81 classes)
Thank you in advance.

**Comment by Sierkinhane** [comment]
Hi, you can refer to [this repository](https://github.com/ZejianLi/LAMA) to obtain YOLO scores. It's important to note that layout-to-image evaluations typically use the 80 classes in COCO. As a result, we utilize YOLOv4 weights available [here](https://github.com/pjreddie/darknet/issues/2135#issuecomment-657199920).
